# Test Groups for Factor Comparison Test Suite
# Generated by test_groups_source.g
# Total: 40 groups
#
# Groups organized by test concern:
#   Part1_*: Pure direct products
#   Part2_*: Single semidirect factor
#   Part3_*: Multiple semidirect factors (bucket 54 pattern)
#   Concern1_*: Pure factor mismatch with semidirect
#   Concern2_*: Greedy matching robustness
#   Edge_*: Edge cases
#
# Fields: source, originalIndex, combinedIndex, index, testName, sigKey, order\
,
#         isDirectProduct, factors, factorOrders, numFactors,
#         histogram, maxOrder, numOrders, factorGens (for DPs)

TEST_GROUPS_GENERATED := [
rec(
  source := "TEST",
  originalIndex := 1,
  combinedIndex := 1,
  index := 1,
  testName := "Part1_C2_x_S4",
  sigKey := [ 48, 12, 10, 3, [ 2, 2 ] ],
  order := 48,
  isDirectProduct := true,
  factors := [ "C2", "S4" ],
  factorOrders := [ 2, 24 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 19 ], [ 3, 8 ], [ 4, 12 ], [ 6, 8 ] ],
  maxOrder := 6,
  numOrders := 5,
  factorGens := [ [ "(1,25)(2,26)(3,27)(4,28)(5,29)(6,30)(7,31)(8,32)(9,33)(10\
,34)(11,35)(12,36)(13,37)(14,38)(15,39)(16,40)(17,41)(18,42)(19,43)(20,44)(21,\
45)(22,46)(23,47)(24,48)" ], [ "(1,9,13)(2,10,14)(3,7,15)(4,8,16)(5,12,17)(6,1\
1,18)(19,22,23)(20,21,24)(25,33,37)(26,34,38)(27,31,39)(28,32,40)(29,36,41)(30\
,35,42)(43,46,47)(44,45,48)", "(1,20,12)(2,19,11)(3,23,10)(4,24,9)(5,21,8)(6,2\
2,7)(13,17,16)(14,18,15)(25,44,36)(26,43,35)(27,47,34)(28,48,33)(29,45,32)(30,\
46,31)(37,41,40)(38,42,39)", "(1,10,17,19)(2,9,18,20)(3,12,14,21)(4,11,13,22)(\
5,7,16,23)(6,8,15,24)(25,34,41,43)(26,33,42,44)(27,36,38,45)(28,35,37,46)(29,3\
1,40,47)(30,32,39,48)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 2,
  combinedIndex := 2,
  index := 2,
  testName := "Part1_S4_x_C2",
  sigKey := [ 48, 12, 10, 3, [ 2, 2 ] ],
  order := 48,
  isDirectProduct := true,
  factors := [ "C2", "S4" ],
  factorOrders := [ 2, 24 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 19 ], [ 3, 8 ], [ 4, 12 ], [ 6, 8 ] ],
  maxOrder := 6,
  numOrders := 5,
  factorGens := [ [ "(1,2)(3,4)(5,6)(7,8)(9,10)(11,12)(13,14)(15,16)(17,18)(19\
,20)(21,22)(23,24)(25,26)(27,28)(29,30)(31,32)(33,34)(35,36)(37,38)(39,40)(41,\
42)(43,44)(45,46)(47,48)" ], [ "(1,17,25)(2,18,26)(3,19,27)(4,20,28)(5,13,29)(\
6,14,30)(7,15,31)(8,16,32)(9,23,33)(10,24,34)(11,21,35)(12,22,36)(37,43,45)(38\
,44,46)(39,41,47)(40,42,48)", "(1,31,41)(2,32,42)(3,29,43)(4,30,44)(5,35,37)(6\
,36,38)(7,33,39)(8,34,40)(9,25,47)(10,26,48)(11,27,45)(12,28,46)(13,19,21)(14,\
20,22)(15,17,23)(16,18,24)", "(1,19,33,37)(2,20,34,38)(3,17,35,39)(4,18,36,40)\
(5,23,27,41)(6,24,28,42)(7,21,25,43)(8,22,26,44)(9,13,31,45)(10,14,32,46)(11,1\
5,29,47)(12,16,30,48)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 3,
  combinedIndex := 3,
  index := 3,
  testName := "Part1_C2_x_C2_x_C4",
  sigKey := [ 16, 1, 16, 1, [ 2, 2, 4 ] ],
  order := 16,
  isDirectProduct := true,
  factors := [ "C2", "C2", "C4" ],
  factorOrders := [ 2, 2, 4 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 7 ], [ 4, 8 ] ],
  maxOrder := 4,
  numOrders := 3,
  factorGens := [ [ "(3,4)" ], [ "(1,2)" ], [ "(5,6,7,8)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 4,
  combinedIndex := 4,
  index := 4,
  testName := "Part1_A4_x_A4",
  sigKey := [ 144, 16, 16, 2, [ 3, 3 ] ],
  order := 144,
  isDirectProduct := true,
  factors := [ "A4", "A4" ],
  factorOrders := [ 12, 12 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 15 ], [ 3, 80 ], [ 6, 48 ] ],
  maxOrder := 6,
  numOrders := 4,
  factorGens := [ [ "(5,6,7)", "(6,7,8)" ], [ "(1,2,3)", "(2,3,4)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 5,
  combinedIndex := 5,
  index := 5,
  testName := "Part1_C3_x_S4",
  sigKey := [ 72, 12, 15, 3, [ 2, 3 ] ],
  order := 72,
  isDirectProduct := true,
  factors := [ "C3", "S4" ],
  factorOrders := [ 3, 24 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 9 ], [ 3, 26 ], [ 4, 6 ], [ 6, 18 ], [ 12, 12 \
] ],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(1,25,49)(2,26,50)(3,27,51)(4,28,52)(5,29,53)(6,30,54)(7,\
31,55)(8,32,56)(9,33,57)(10,34,58)(11,35,59)(12,36,60)(13,37,61)(14,38,62)(15,\
39,63)(16,40,64)(17,41,65)(18,42,66)(19,43,67)(20,44,68)(21,45,69)(22,46,70)(2\
3,47,71)(24,48,72)" ], [ "(1,9,13)(2,10,14)(3,7,15)(4,8,16)(5,12,17)(6,11,18)(\
19,22,23)(20,21,24)(25,33,37)(26,34,38)(27,31,39)(28,32,40)(29,36,41)(30,35,42\
)(43,46,47)(44,45,48)(49,57,61)(50,58,62)(51,55,63)(52,56,64)(53,60,65)(54,59,\
66)(67,70,71)(68,69,72)", "(1,16,21)(2,15,22)(3,18,19)(4,17,20)(5,13,24)(6,14,\
23)(7,10,11)(8,9,12)(25,40,45)(26,39,46)(27,42,43)(28,41,44)(29,37,48)(30,38,4\
7)(31,34,35)(32,33,36)(49,64,69)(50,63,70)(51,66,67)(52,65,68)(53,61,72)(54,62\
,71)(55,58,59)(56,57,60)", "(1,10,17,19)(2,9,18,20)(3,12,14,21)(4,11,13,22)(5,\
7,16,23)(6,8,15,24)(25,34,41,43)(26,33,42,44)(27,36,38,45)(28,35,37,46)(29,31,\
40,47)(30,32,39,48)(49,58,65,67)(50,57,66,68)(51,60,62,69)(52,59,61,70)(53,55,\
64,71)(54,56,63,72)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 6,
  combinedIndex := 6,
  index := 6,
  testName := "Part2_D8_x_C3",
  sigKey := [ 24, 2, 15, 2, [ 2, 2, 3 ] ],
  order := 24,
  isDirectProduct := true,
  factors := [ "C3", "D8" ],
  factorOrders := [ 3, 8 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 5 ], [ 3, 2 ], [ 4, 2 ], [ 6, 10 ], [ 12, 4 ] \
],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(5,6,7)" ], [ "(2,4)", "(1,2)(3,4)", "(1,3)(2,4)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 7,
  combinedIndex := 7,
  index := 7,
  testName := "Part2_Q8_x_C3",
  sigKey := [ 24, 2, 15, 2, [ 2, 2, 3 ] ],
  order := 24,
  isDirectProduct := true,
  factors := [ "C3", "Q8" ],
  factorOrders := [ 3, 8 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 1 ], [ 3, 2 ], [ 4, 6 ], [ 6, 2 ], [ 12, 12 ] \
],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(9,10,11)" ], [ "(1,5,2,6)(3,8,4,7)", "(1,3,2,4)(5,7,6,8)\
", "(1,2)(3,4)(5,6)(7,8)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 8,
  combinedIndex := 8,
  index := 8,
  testName := "Part2_D8_x_C5",
  sigKey := [ 40, 2, 25, 2, [ 2, 2, 5 ] ],
  order := 40,
  isDirectProduct := true,
  factors := [ "C5", "D8" ],
  factorOrders := [ 5, 8 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 5 ], [ 4, 2 ], [ 5, 4 ], [ 10, 20 ], [ 20, 8 ]\
 ],
  maxOrder := 20,
  numOrders := 6,
  factorGens := [ [ "(5,6,7,8,9)" ], [ "(2,4)", "(1,2)(3,4)", "(1,3)(2,4)" ] ]\
 ),
rec(
  source := "TEST",
  originalIndex := 9,
  combinedIndex := 9,
  index := 9,
  testName := "Part2_D8_x_C7",
  sigKey := [ 56, 2, 35, 2, [ 2, 2, 7 ] ],
  order := 56,
  isDirectProduct := true,
  factors := [ "C7", "D8" ],
  factorOrders := [ 7, 8 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 5 ], [ 4, 2 ], [ 7, 6 ], [ 14, 30 ], [ 28, 12 \
] ],
  maxOrder := 28,
  numOrders := 6,
  factorGens := [ [ "(5,6,7,8,9,10,11)" ], [ "(2,4)", "(1,2)(3,4)", "(1,3)(2,4\
)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 10,
  combinedIndex := 10,
  index := 10,
  testName := "Part2_SG24_12_x_C2",
  sigKey := [ 48, 12, 10, 3, [ 2, 2 ] ],
  order := 48,
  isDirectProduct := true,
  factors := [ "C2", "S4" ],
  factorOrders := [ 2, 24 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 19 ], [ 3, 8 ], [ 4, 12 ], [ 6, 8 ] ],
  maxOrder := 6,
  numOrders := 5,
  factorGens := [ [ "(1,3)(2,5)(4,6)" ], [ "(1,4,2)(3,6,5)", "(1,6,2)(3,4,5)",\
 "(2,4,5,6)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 11,
  combinedIndex := 11,
  index := 11,
  testName := "Part3_SG32_6_x_SG72_40",
  sigKey := [ 2304, 72, 99, 3, [ 2, 2, 2, 4 ] ],
  order := 2304,
  isDirectProduct := true,
  factors := [ "(C2 x C2 x C2) : C4", "(S3 x S3) : C2" ],
  factorOrders := [ 32, 72 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 263 ], [ 3, 8 ], [ 4, 1016 ], [ 6, 376 ], [ 12\
, 640 ] ],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(7,9)(8,10,13,11)(12,14)", "(8,13)(10,11)", "(7,14)(8,13)\
(9,12)(10,11)", "(9,12)(10,11)", "(7,8)(9,11)(10,12)(13,14)" ], [ "(4,5)(7,14)\
(8,13)(9,12)(10,11)", "(3,6)(4,5)", "(1,2)(3,5)(4,6)(7,14)(8,13)(9,12)(10,11)"\
, "(2,5,4)", "(1,6,3)(2,5,4)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 12,
  combinedIndex := 12,
  index := 12,
  testName := "Part3_SG32_7_x_SG72_40",
  sigKey := [ 2304, 72, 99, 3, [ 2, 2, 2, 4 ] ],
  order := 2304,
  isDirectProduct := true,
  factors := [ "(C8 : C2) : C2", "(S3 x S3) : C2" ],
  factorOrders := [ 32, 72 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 263 ], [ 3, 8 ], [ 4, 376 ], [ 6, 376 ], [ 8, \
640 ], [ 12, 128 ], [ 24, 512 ] ],
  maxOrder := 24,
  numOrders := 8,
  factorGens := [ [ "(7,8,9,11,13,14,10,12)", "(7,9,13,10)(8,11,14,12)", "(7,1\
3)(8,14)(9,10)(11,12)", "(7,13)(9,10)", "(9,10)(11,12)" ], [ "(4,5)(7,13)(8,14\
)(9,10)(11,12)", "(3,6)(4,5)", "(1,2)(3,5)(4,6)(7,13)(8,14)(9,10)(11,12)", "(1\
,3,6)", "(1,3,6)(2,4,5)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 13,
  combinedIndex := 13,
  index := 13,
  testName := "Part3_SG32_7_x_SG72_41",
  sigKey := [ 2304, 72, 66, 3, [ 2, 2, 2, 4 ] ],
  order := 2304,
  isDirectProduct := true,
  factors := [ "(C8 : C2) : C2", "(C3 x C3) : Q8" ],
  factorOrders := [ 32, 72 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 119 ], [ 3, 8 ], [ 4, 904 ], [ 6, 88 ], [ 8, 1\
024 ], [ 12, 32 ], [ 24, 128 ] ],
  maxOrder := 24,
  numOrders := 8,
  factorGens := [ [ "(1,2,3,5,7,8,4,6)", "(1,3,7,4)(2,5,8,6)", "(1,7)(2,8)(3,4\
)(5,6)", "(1,7)(3,4)", "(3,4)(5,6)" ], [ "(1,7)(2,8)(3,4)(5,6)(10,15,13,16)(11\
,12,14,17)", "(1,7)(2,8)(3,4)(5,6)(10,11,13,14)(12,15,17,16)", "(9,12)(10,15)(\
11,16)(13,14)", "(9,17,12)(10,16,14)(11,15,13)", "(9,13,10)(11,16,17)(12,15,14\
)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 14,
  combinedIndex := 14,
  index := 14,
  testName := "Part3_SG32_6_x_C3",
  sigKey := [ 96, 4, 33, 2, [ 2, 3, 4 ] ],
  order := 96,
  isDirectProduct := true,
  factors := [ "C3", "(C2 x C2 x C2) : C4" ],
  factorOrders := [ 3, 32 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 11 ], [ 3, 2 ], [ 4, 20 ], [ 6, 22 ], [ 12, 40\
 ] ],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(9,10,11)" ], [ "(1,2)(3,7,6,8)(4,5)", "(1,3)(2,8)(4,6)(5\
,7)", "(2,5)(7,8)", "(3,6)(7,8)", "(1,4)(2,5)(3,6)(7,8)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 15,
  combinedIndex := 15,
  index := 15,
  testName := "Part3_SG32_6_x_C5",
  sigKey := [ 160, 4, 55, 2, [ 2, 4, 5 ] ],
  order := 160,
  isDirectProduct := true,
  factors := [ "C5", "(C2 x C2 x C2) : C4" ],
  factorOrders := [ 5, 32 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 11 ], [ 4, 20 ], [ 5, 4 ], [ 10, 44 ], [ 20, 8\
0 ] ],
  maxOrder := 20,
  numOrders := 6,
  factorGens := [ [ "(9,10,11,12,13)" ], [ "(1,2)(3,7,6,8)(4,5)", "(1,3)(2,8)(\
4,6)(5,7)", "(2,5)(7,8)", "(3,6)(7,8)", "(1,4)(2,5)(3,6)(7,8)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 16,
  combinedIndex := 16,
  index := 16,
  testName := "Concern1_C2_x_C3_x_D8",
  sigKey := [ 48, 2, 30, 2, [ 2, 2, 2, 3 ] ],
  order := 48,
  isDirectProduct := true,
  factors := [ "C2", "C3", "D8" ],
  factorOrders := [ 2, 3, 8 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 11 ], [ 3, 2 ], [ 4, 4 ], [ 6, 22 ], [ 12, 8 ]\
 ],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(1,2)" ], [ "(7,8,9)" ], [ "(3,5)(4,6)", "(4,6)", "(3,4)(\
5,6)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 17,
  combinedIndex := 17,
  index := 17,
  testName := "Concern1_C2_x_C5_x_D8",
  sigKey := [ 80, 2, 50, 2, [ 2, 2, 2, 5 ] ],
  order := 80,
  isDirectProduct := true,
  factors := [ "C2", "C5", "D8" ],
  factorOrders := [ 2, 5, 8 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 11 ], [ 4, 4 ], [ 5, 4 ], [ 10, 44 ], [ 20, 16\
 ] ],
  maxOrder := 20,
  numOrders := 6,
  factorGens := [ [ "(1,2)" ], [ "(7,8,9,10,11)" ], [ "(3,5)(4,6)", "(4,6)", "\
(3,4)(5,6)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 18,
  combinedIndex := 18,
  index := 18,
  testName := "Concern1_C2_x_C2_x_C3_x_D8",
  sigKey := [ 96, 2, 60, 2, [ 2, 2, 2, 2, 3 ] ],
  order := 96,
  isDirectProduct := true,
  factors := [ "C2", "C2", "C3", "D8" ],
  factorOrders := [ 2, 2, 3, 8 ],
  numFactors := 4,
  histogram := [ [ 1, 1 ], [ 2, 23 ], [ 3, 2 ], [ 4, 8 ], [ 6, 46 ], [ 12, 16 \
] ],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(3,4)" ], [ "(1,2)(3,4)" ], [ "(9,10,11)" ], [ "(5,7)(6,8\
)", "(3,4)(5,6)(7,8)", "(6,8)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 19,
  combinedIndex := 19,
  index := 19,
  testName := "Concern1_C2_x_C2_x_C7_x_D8",
  sigKey := [ 224, 2, 140, 2, [ 2, 2, 2, 2, 7 ] ],
  order := 224,
  isDirectProduct := true,
  factors := [ "C2", "C2", "C7", "D8" ],
  factorOrders := [ 2, 2, 7, 8 ],
  numFactors := 4,
  histogram := [ [ 1, 1 ], [ 2, 23 ], [ 4, 8 ], [ 7, 6 ], [ 14, 138 ], [ 28, 4\
8 ] ],
  maxOrder := 28,
  numOrders := 6,
  factorGens := [ [ "(3,4)" ], [ "(1,2)(3,4)" ], [ "(9,10,11,12,13,14,15)" ], \
[ "(5,7)(6,8)", "(3,4)(5,6)(7,8)", "(6,8)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 20,
  combinedIndex := 20,
  index := 20,
  testName := "Concern1_C3_x_D8_x_Q8",
  sigKey := [ 192, 4, 75, 2, [ 2, 2, 2, 2, 3 ] ],
  order := 192,
  isDirectProduct := true,
  factors := [ "C3", "D8", "Q8" ],
  factorOrders := [ 3, 8, 8 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 11 ], [ 3, 2 ], [ 4, 52 ], [ 6, 22 ], [ 12, 10\
4 ] ],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(21,22,23)" ], [ "(2,4)(5,6)(7,11)(8,12)(9,10)(13,19)(14,\
17)(15,20)(16,18)", "(1,3)(2,4)(5,9)(6,10)(7,14)(8,16)(11,17)(12,18)(13,15)(19\
,20)", "(1,2)(3,4)(6,10)(11,17)(12,18)(19,20)" ], [ "(5,16,9,8)(6,18,10,12)(7,\
15,14,13)(11,20,17,19)", "(5,14,9,7)(6,17,10,11)(8,13,16,15)(12,19,18,20)", "(\
5,9)(6,10)(7,14)(8,16)(11,17)(12,18)(13,15)(19,20)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 21,
  combinedIndex := 21,
  index := 21,
  testName := "Concern1_C5_x_D8_x_Q8",
  sigKey := [ 320, 4, 125, 2, [ 2, 2, 2, 2, 5 ] ],
  order := 320,
  isDirectProduct := true,
  factors := [ "C5", "D8", "Q8" ],
  factorOrders := [ 5, 8, 8 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 11 ], [ 4, 52 ], [ 5, 4 ], [ 10, 44 ], [ 20, 2\
08 ] ],
  maxOrder := 20,
  numOrders := 6,
  factorGens := [ [ "(21,22,23,24,25)" ], [ "(2,4)(5,6)(7,11)(8,12)(9,10)(13,1\
9)(14,17)(15,20)(16,18)", "(1,3)(2,4)(5,9)(6,10)(7,14)(8,16)(11,17)(12,18)(13,\
15)(19,20)", "(1,2)(3,4)(6,10)(11,17)(12,18)(19,20)" ], [ "(5,16,9,8)(6,18,10,\
12)(7,15,14,13)(11,20,17,19)", "(5,14,9,7)(6,17,10,11)(8,13,16,15)(12,19,18,20\
)", "(5,9)(6,10)(7,14)(8,16)(11,17)(12,18)(13,15)(19,20)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 22,
  combinedIndex := 22,
  index := 22,
  testName := "Concern1_C2_x_C3_x_Q8",
  sigKey := [ 48, 2, 30, 2, [ 2, 2, 2, 3 ] ],
  order := 48,
  isDirectProduct := true,
  factors := [ "C2", "C3", "Q8" ],
  factorOrders := [ 2, 3, 8 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 3 ], [ 3, 2 ], [ 4, 12 ], [ 6, 6 ], [ 12, 24 ]\
 ],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(1,2)" ], [ "(11,12,13)" ], [ "(3,6)(4,8)(5,9)(7,10)", "(\
3,5,6,9)(4,7,8,10)", "(3,4,6,8)(5,10,9,7)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 23,
  combinedIndex := 23,
  index := 23,
  testName := "Concern1_C3_x_D8",
  sigKey := [ 24, 2, 15, 2, [ 2, 2, 3 ] ],
  order := 24,
  isDirectProduct := true,
  factors := [ "C3", "D8" ],
  factorOrders := [ 3, 8 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 5 ], [ 3, 2 ], [ 4, 2 ], [ 6, 10 ], [ 12, 4 ] \
],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(5,6,7)" ], [ "(2,4)", "(1,2)(3,4)", "(1,3)(2,4)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 24,
  combinedIndex := 24,
  index := 24,
  testName := "Concern1_C5_x_D8",
  sigKey := [ 40, 2, 25, 2, [ 2, 2, 5 ] ],
  order := 40,
  isDirectProduct := true,
  factors := [ "C5", "D8" ],
  factorOrders := [ 5, 8 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 5 ], [ 4, 2 ], [ 5, 4 ], [ 10, 20 ], [ 20, 8 ]\
 ],
  maxOrder := 20,
  numOrders := 6,
  factorGens := [ [ "(5,6,7,8,9)" ], [ "(2,4)", "(1,2)(3,4)", "(1,3)(2,4)" ] ]\
 ),
rec(
  source := "TEST",
  originalIndex := 25,
  combinedIndex := 25,
  index := 25,
  testName := "Concern1_C3_x_C5_x_D8",
  sigKey := [ 120, 2, 75, 2, [ 2, 2, 3, 5 ] ],
  order := 120,
  isDirectProduct := true,
  factors := [ "C3", "C5", "D8" ],
  factorOrders := [ 3, 5, 8 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 5 ], [ 3, 2 ], [ 4, 2 ], [ 5, 4 ], [ 6, 10 ], \
[ 10, 20 ], [ 12, 4 ], [ 15, 8 ], [ 20, 8 ], [ 30, 40 ], [ 60, 16 ] ],
  maxOrder := 60,
  numOrders := 12,
  factorGens := [ [ "(5,6,7)" ], [ "(8,9,10,11,12)" ], [ "(2,4)", "(1,2)(3,4)"\
, "(1,3)(2,4)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 26,
  combinedIndex := 26,
  index := 26,
  testName := "Concern1_C7_x_C11_x_D8",
  sigKey := [ 616, 2, 385, 2, [ 2, 2, 7, 11 ] ],
  order := 616,
  isDirectProduct := true,
  factors := [ "C7", "D8", "C11" ],
  factorOrders := [ 7, 8, 11 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 5 ], [ 4, 2 ], [ 7, 6 ], [ 11, 10 ], [ 14, 30 \
], [ 22, 50 ], [ 28, 12 ], [ 44, 20 ], [ 77, 60 ], [ 154, 300 ], [ 308, 120 ] \
],
  maxOrder := 308,
  numOrders := 12,
  factorGens := [ [ "(5,6,7,8,9,10,11)" ], [ "(2,4)", "(1,2)(3,4)", "(1,3)(2,4\
)" ], [ "(12,13,14,15,16,17,18,19,20,21,22)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 27,
  combinedIndex := 27,
  index := 27,
  testName := "Concern1_C3_x_C2_x_D8",
  sigKey := [ 48, 2, 30, 2, [ 2, 2, 2, 3 ] ],
  order := 48,
  isDirectProduct := true,
  factors := [ "C2", "C3", "D8" ],
  factorOrders := [ 2, 3, 8 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 11 ], [ 3, 2 ], [ 4, 4 ], [ 6, 22 ], [ 12, 8 ]\
 ],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(1,2)" ], [ "(7,8,9)" ], [ "(3,5)(4,6)", "(4,6)", "(3,4)(\
5,6)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 28,
  combinedIndex := 28,
  index := 28,
  testName := "Concern2_D8_x_D8",
  sigKey := [ 64, 4, 25, 2, [ 2, 2, 2, 2 ] ],
  order := 64,
  isDirectProduct := true,
  factors := [ "D8", "D8" ],
  factorOrders := [ 8, 8 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 35 ], [ 4, 28 ] ],
  maxOrder := 4,
  numOrders := 3,
  factorGens := [ [ "(5,11)(6,12)(7,8)(9,10)", "(5,7)(6,9)(8,11)(10,12)", "(8,\
11)(10,12)" ], [ "(2,4)(6,9)(10,12)", "(1,3)(2,4)(5,7)(6,9)(8,11)(10,12)", "(1\
,2)(3,4)(5,6)(7,9)(8,10)(11,12)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 29,
  combinedIndex := 29,
  index := 29,
  testName := "Concern2_D8_x_Q8",
  sigKey := [ 64, 4, 25, 2, [ 2, 2, 2, 2 ] ],
  order := 64,
  isDirectProduct := true,
  factors := [ "D8", "Q8" ],
  factorOrders := [ 8, 8 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 11 ], [ 4, 52 ] ],
  maxOrder := 4,
  numOrders := 3,
  factorGens := [ [ "(2,4)(5,6)(7,10)(8,11)(9,12)(13,17)(14,18)(15,19)(16,20)"\
, "(1,3)(2,4)(5,7)(6,10)(8,13)(9,14)(11,17)(12,18)(15,16)(19,20)", "(1,2)(3,4)\
(6,10)(11,17)(12,18)(19,20)" ], [ "(5,14,7,9)(6,18,10,12)(8,16,13,15)(11,20,17\
,19)", "(5,8,7,13)(6,11,10,17)(9,16,14,15)(12,20,18,19)", "(5,7)(6,10)(8,13)(9\
,14)(11,17)(12,18)(15,16)(19,20)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 30,
  combinedIndex := 30,
  index := 30,
  testName := "Concern2_Q8_x_D8",
  sigKey := [ 64, 4, 25, 2, [ 2, 2, 2, 2 ] ],
  order := 64,
  isDirectProduct := true,
  factors := [ "D8", "Q8" ],
  factorOrders := [ 8, 8 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 11 ], [ 4, 52 ] ],
  maxOrder := 4,
  numOrders := 3,
  factorGens := [ [ "(9,14)(10,18)(11,21)(12,23)(13,19)(15,22)(16,24)(17,20)",\
 "(9,12)(10,16)(11,20)(13,22)(14,23)(15,19)(17,21)(18,24)", "(9,22)(10,21)(11,\
24)(12,13)(14,19)(15,23)(16,17)(18,20)" ], [ "(1,7,4,5)(2,3,6,8)(9,19,12,15)(1\
0,11,16,20)(13,23,22,14)(17,18,21,24)", "(1,2,4,6)(3,7,8,5)(9,10,12,16)(11,19,\
20,15)(13,17,22,21)(14,18,23,24)", "(1,4)(2,6)(3,8)(5,7)(9,12)(10,16)(11,20)(1\
3,22)(14,23)(15,19)(17,21)(18,24)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 31,
  combinedIndex := 31,
  index := 31,
  testName := "Concern2_D8_x_D8_x_Q8",
  sigKey := [ 512, 8, 125, 2, [ 2, 2, 2, 2, 2, 2 ] ],
  order := 512,
  isDirectProduct := true,
  factors := [ "D8", "D8", "Q8" ],
  factorOrders := [ 8, 8, 8 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 71 ], [ 4, 440 ] ],
  maxOrder := 4,
  numOrders := 3,
  factorGens := [ [ "(1,3)(2,4)(5,11)(6,12)(7,8)(9,10)(13,23)(14,30)(15,16)(17\
,37)(18,38)(19,20)(21,41)(22,42)(24,26)(25,27)(28,40)(29,39)(31,33)(32,34)(35,\
44)(36,43)", "(5,7)(6,9)(8,11)(10,12)(13,15)(14,19)(16,23)(17,24)(18,25)(20,30\
)(21,31)(22,32)(26,37)(27,38)(28,29)(33,41)(34,42)(35,36)(39,40)(43,44)", "(1,\
3)(2,4)(5,7)(6,9)(13,15)(14,19)(17,24)(18,25)(21,31)(22,32)(28,29)(35,36)" ], \
[ "(1,4)(2,3)(5,9)(6,7)(8,12)(10,11)(13,14)(15,19)(16,20)(17,21)(18,22)(23,30)\
(24,31)(25,32)(26,33)(27,34)(28,35)(29,36)(37,41)(38,42)(39,43)(40,44)", "(1,4\
,3,2)(5,6,7,9)(8,10,11,12)(13,14,15,19)(16,20,23,30)(17,21,24,31)(18,22,25,32)\
(26,33,37,41)(27,34,38,42)(28,35,29,36)(39,43,40,44)", "(1,3)(2,4)(5,7)(6,9)(8\
,11)(10,12)(13,15)(14,19)(16,23)(17,24)(18,25)(20,30)(21,31)(22,32)(26,37)(27,\
38)(28,29)(33,41)(34,42)(35,36)(39,40)(43,44)" ], [ "(1,3)(2,4)(5,7)(6,9)(8,11\
)(10,12)(13,18,15,25)(14,22,19,32)(16,27,23,38)(17,28,24,29)(20,34,30,42)(21,3\
5,31,36)(26,39,37,40)(33,43,41,44)", "(1,3)(2,4)(5,7)(6,9)(8,11)(10,12)(13,17,\
15,24)(14,21,19,31)(16,26,23,37)(18,29,25,28)(20,33,30,41)(22,36,32,35)(27,40,\
38,39)(34,44,42,43)", "(13,15)(14,19)(16,23)(17,24)(18,25)(20,30)(21,31)(22,32\
)(26,37)(27,38)(28,29)(33,41)(34,42)(35,36)(39,40)(43,44)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 32,
  combinedIndex := 32,
  index := 32,
  testName := "Concern2_Q8_x_D8_x_D8",
  sigKey := [ 512, 8, 125, 2, [ 2, 2, 2, 2, 2, 2 ] ],
  order := 512,
  isDirectProduct := true,
  factors := [ "D8", "D8", "Q8" ],
  factorOrders := [ 8, 8, 8 ],
  numFactors := 3,
  histogram := [ [ 1, 1 ], [ 2, 71 ], [ 4, 440 ] ],
  maxOrder := 4,
  numOrders := 3,
  factorGens := [ [ "(1,4)(2,6)(3,8)(5,7)(25,30)(26,34)(27,38)(28,40)(29,41)(3\
1,43)(32,45)(33,46)(35,48)(36,50)(37,51)(39,52)(42,53)(44,54)(47,55)(49,56)", \
"(25,28)(26,32)(27,36)(29,39)(30,40)(31,35)(33,44)(34,45)(37,49)(38,50)(41,52)\
(42,47)(43,48)(46,54)(51,56)(53,55)", "(30,40)(34,45)(38,50)(41,52)(43,48)(46,\
54)(51,56)(53,55)" ], [ "(1,4)(2,6)(3,8)(5,7)(9,14)(10,18)(11,21)(12,23)(13,19\
)(15,22)(16,24)(17,20)(25,29)(26,33)(27,37)(28,39)(30,41)(31,42)(32,44)(34,46)\
(35,47)(36,49)(38,51)(40,52)(43,53)(45,54)(48,55)(50,56)", "(9,12)(10,16)(11,2\
0)(13,22)(14,23)(15,19)(17,21)(18,24)(25,28)(26,32)(27,36)(29,39)(30,40)(31,35\
)(33,44)(34,45)(37,49)(38,50)(41,52)(42,47)(43,48)(46,54)(51,56)(53,55)", "(1,\
4)(2,6)(3,8)(5,7)(9,13)(10,17)(11,18)(12,22)(14,15)(16,21)(19,23)(20,24)(29,39\
)(33,44)(37,49)(41,52)(42,47)(46,54)(51,56)(53,55)" ], [ "(1,3,4,8)(2,5,6,7)(9\
,20,12,11)(10,19,16,15)(13,24,22,18)(14,17,23,21)(25,27,28,36)(26,31,32,35)(29\
,37,39,49)(30,38,40,50)(33,42,44,47)(34,43,45,48)(41,51,52,56)(46,53,54,55)", \
"(1,6,4,2)(3,5,8,7)(9,10,12,16)(11,19,20,15)(13,17,22,21)(14,18,23,24)(25,26,2\
8,32)(27,35,36,31)(29,33,39,44)(30,34,40,45)(37,47,49,42)(38,48,50,43)(41,46,5\
2,54)(51,55,56,53)", "(1,4)(2,6)(3,8)(5,7)(9,12)(10,16)(11,20)(13,22)(14,23)(1\
5,19)(17,21)(18,24)(25,28)(26,32)(27,36)(29,39)(30,40)(31,35)(33,44)(34,45)(37\
,49)(38,50)(41,52)(42,47)(43,48)(46,54)(51,56)(53,55)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 33,
  combinedIndex := 33,
  index := 33,
  testName := "Concern2_C2_x_C3_x_D8_x_Q8",
  sigKey := [ 384, 4, 150, 2, [ 2, 2, 2, 2, 2, 3 ] ],
  order := 384,
  isDirectProduct := true,
  factors := [ "C2", "C3", "D8", "Q8" ],
  factorOrders := [ 2, 3, 8, 8 ],
  numFactors := 4,
  histogram := [ [ 1, 1 ], [ 2, 23 ], [ 3, 2 ], [ 4, 104 ], [ 6, 46 ], [ 12, 2\
08 ] ],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(1,2)" ], [ "(23,24,25)" ], [ "(5,6)(9,12)(15,19)(16,20)(\
21,22)", "(3,5)(4,6)(7,9)(8,12)(10,15)(11,16)(13,19)(14,20)(17,21)(18,22)", "(\
3,4)(5,6)(7,8)(9,12)(10,13)(11,14)(15,19)(16,20)(17,18)(21,22)" ], [ "(7,13,8,\
10)(9,19,12,15)(11,17,14,18)(16,21,20,22)", "(7,14,8,11)(9,20,12,16)(10,18,13,\
17)(15,22,19,21)", "(7,8)(9,12)(10,13)(11,14)(15,19)(16,20)(17,18)(21,22)" ] ]\
 ),
rec(
  source := "TEST",
  originalIndex := 34,
  combinedIndex := 34,
  index := 34,
  testName := "Concern2_C3_x_Q8_x_C2_x_D8",
  sigKey := [ 384, 4, 150, 2, [ 2, 2, 2, 2, 2, 3 ] ],
  order := 384,
  isDirectProduct := true,
  factors := [ "C2", "C3", "D8", "Q8" ],
  factorOrders := [ 2, 3, 8, 8 ],
  numFactors := 4,
  histogram := [ [ 1, 1 ], [ 2, 23 ], [ 3, 2 ], [ 4, 104 ], [ 6, 46 ], [ 12, 2\
08 ] ],
  maxOrder := 12,
  numOrders := 6,
  factorGens := [ [ "(1,2)" ], [ "(27,28,29)" ], [ "(11,15)(12,19)(13,20)(14,2\
4)(16,17)(18,23)(21,25)(22,26)", "(11,16)(12,20)(13,23)(14,25)(15,21)(17,24)(1\
8,26)(19,22)", "(11,14)(12,18)(13,22)(15,24)(16,25)(17,21)(19,23)(20,26)" ], [\
 "(3,4,6,8)(5,9,10,7)(11,12,14,18)(13,21,22,17)(15,19,24,23)(16,20,25,26)", "(\
3,5,6,10)(4,7,8,9)(11,13,14,22)(12,17,18,21)(15,20,24,26)(16,23,25,19)", "(3,6\
)(4,8)(5,10)(7,9)(11,14)(12,18)(13,22)(15,24)(16,25)(17,21)(19,23)(20,26)" ] ]\
 ),
rec(
  source := "TEST",
  originalIndex := 35,
  combinedIndex := 35,
  index := 35,
  testName := "Concern2_D8_x_D16",
  sigKey := [ 128, 8, 35, 2, [ 2, 2, 2, 2 ] ],
  order := 128,
  isDirectProduct := true,
  factors := [ "D8", "D16" ],
  factorOrders := [ 8, 16 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 59 ], [ 4, 36 ], [ 8, 32 ] ],
  maxOrder := 8,
  numOrders := 4,
  factorGens := [ [ "(2,5)(6,8)(9,10)(11,14)(12,15)(13,16)(17,21)(18,22)(19,23\
)(20,24)", "(1,3)(2,5)(4,7)(6,8)(9,11)(10,14)(12,17)(13,18)(15,21)(16,22)(19,2\
0)(23,24)", "(1,2)(3,5)(4,6)(7,8)(10,14)(15,21)(16,22)(23,24)" ], [ "(1,7)(2,8\
)(3,4)(5,6)(9,11)(10,14)(12,19)(15,23)(17,20)(21,24)", "(1,3)(2,5)(4,7)(6,8)(9\
,13,11,18)(10,16,14,22)(12,19,17,20)(15,23,21,24)", "(1,3)(2,5)(9,12)(10,15)(1\
1,17)(13,20)(14,21)(16,24)(18,19)(22,23)", "(9,11)(10,14)(12,17)(13,18)(15,21)\
(16,22)(19,20)(23,24)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 36,
  combinedIndex := 36,
  index := 36,
  testName := "Concern2_Q8_x_QD16",
  sigKey := [ 128, 8, 35, 2, [ 2, 2, 2, 2 ] ],
  order := 128,
  isDirectProduct := true,
  factors := [ "Q8", "Q16" ],
  factorOrders := [ 8, 16 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 3 ], [ 4, 92 ], [ 8, 32 ] ],
  maxOrder := 8,
  numOrders := 4,
  factorGens := [ [ "(1,12,4,3)(2,11,8,7)(5,16,14,10)(6,9,15,13)(17,26,20,19)(\
18,22,24,23)(21,29,28,27)(25,31,32,30)", "(1,2,4,8)(3,11,12,7)(5,9,14,13)(6,10\
,15,16)(17,18,20,24)(19,22,26,23)(21,25,28,32)(27,31,29,30)", "(1,4)(2,8)(3,12\
)(5,14)(6,15)(7,11)(9,13)(10,16)(17,20)(18,24)(19,26)(21,28)(22,23)(25,32)(27,\
29)(30,31)" ], [ "(1,7,4,11)(2,3,8,12)(5,15,14,6)(9,16,13,10)(17,27,23,25,20,2\
9,22,32)(18,31,19,28,24,30,26,21)", "(1,4)(2,8)(3,12)(5,14)(6,15)(7,11)(9,13)(\
10,16)(17,23,20,22)(18,19,24,26)(21,31,28,30)(25,29,32,27)", "(1,14)(2,13)(3,1\
6)(4,5)(6,11)(7,15)(8,9)(10,12)(17,21,20,28)(18,25,24,32)(19,27,26,29)(22,31,2\
3,30)", "(17,20)(18,24)(19,26)(21,28)(22,23)(25,32)(27,29)(30,31)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 37,
  combinedIndex := 37,
  index := 37,
  testName := "Concern2_Dihedral8_x_Quaternion8",
  sigKey := [ 64, 4, 25, 2, [ 2, 2, 2, 2 ] ],
  order := 64,
  isDirectProduct := true,
  factors := [ "D8", "Q8" ],
  factorOrders := [ 8, 8 ],
  numFactors := 2,
  histogram := [ [ 1, 1 ], [ 2, 11 ], [ 4, 52 ] ],
  maxOrder := 4,
  numOrders := 3,
  factorGens := [ [ "(2,3)", "(1,4)(2,3)", "(1,2)(3,4)" ], [ "(5,7,8,12)(6,9,1\
0,11)", "(5,6,8,10)(7,11,12,9)", "(5,8)(6,10)(7,12)(9,11)" ] ] ),
rec(
  source := "TEST",
  originalIndex := 38,
  combinedIndex := 38,
  index := 38,
  testName := "Edge_S5_nonsplit",
  sigKey := [ 120, 60, 7, -1, [ 2 ] ],
  order := 120,
  isDirectProduct := false,
  factors := [  ],
  factorOrders := [  ],
  numFactors := 1,
  histogram := [ [ 1, 1 ], [ 2, 25 ], [ 3, 20 ], [ 4, 30 ], [ 5, 24 ], [ 6, 20\
 ] ],
  maxOrder := 6,
  numOrders := 6 ),
rec(
  source := "TEST",
  originalIndex := 39,
  combinedIndex := 39,
  index := 39,
  testName := "Edge_S4_x_trivial",
  sigKey := [ 24, 12, 5, 3, [ 2 ] ],
  order := 24,
  isDirectProduct := false,
  factors := [  ],
  factorOrders := [  ],
  numFactors := 1,
  histogram := [ [ 1, 1 ], [ 2, 9 ], [ 3, 8 ], [ 4, 6 ] ],
  maxOrder := 4,
  numOrders := 4 ),
rec(
  source := "TEST",
  originalIndex := 40,
  combinedIndex := 40,
  index := 40,
  testName := "Edge_S4_alone",
  sigKey := [ 24, 12, 5, 3, [ 2 ] ],
  order := 24,
  isDirectProduct := false,
  factors := [  ],
  factorOrders := [  ],
  numFactors := 1,
  histogram := [ [ 1, 1 ], [ 2, 9 ], [ 3, 8 ], [ 4, 6 ] ],
  maxOrder := 4,
  numOrders := 4 )
];

# Group construction expressions (for reference/reconstruction)
TEST_GROUP_CONSTRUCTORS := rec(
  Part1_C2_x_S4 := 1,
  Part1_S4_x_C2 := 2,
  Part1_C2_x_C2_x_C4 := 3,
  Part1_A4_x_A4 := 4,
  Part1_C3_x_S4 := 5,
  Part2_D8_x_C3 := 6,
  Part2_Q8_x_C3 := 7,
  Part2_D8_x_C5 := 8,
  Part2_D8_x_C7 := 9,
  Part2_SG24_12_x_C2 := 10,
  Part3_SG32_6_x_SG72_40 := 11,
  Part3_SG32_7_x_SG72_40 := 12,
  Part3_SG32_7_x_SG72_41 := 13,
  Part3_SG32_6_x_C3 := 14,
  Part3_SG32_6_x_C5 := 15,
  Concern1_C2_x_C3_x_D8 := 16,
  Concern1_C2_x_C5_x_D8 := 17,
  Concern1_C2_x_C2_x_C3_x_D8 := 18,
  Concern1_C2_x_C2_x_C7_x_D8 := 19,
  Concern1_C3_x_D8_x_Q8 := 20,
  Concern1_C5_x_D8_x_Q8 := 21,
  Concern1_C2_x_C3_x_Q8 := 22,
  Concern1_C3_x_D8 := 23,
  Concern1_C5_x_D8 := 24,
  Concern1_C3_x_C5_x_D8 := 25,
  Concern1_C7_x_C11_x_D8 := 26,
  Concern1_C3_x_C2_x_D8 := 27,
  Concern2_D8_x_D8 := 28,
  Concern2_D8_x_Q8 := 29,
  Concern2_Q8_x_D8 := 30,
  Concern2_D8_x_D8_x_Q8 := 31,
  Concern2_Q8_x_D8_x_D8 := 32,
  Concern2_C2_x_C3_x_D8_x_Q8 := 33,
  Concern2_C3_x_Q8_x_C2_x_D8 := 34,
  Concern2_D8_x_D16 := 35,
  Concern2_Q8_x_QD16 := 36,
  Concern2_Dihedral8_x_Quaternion8 := 37,
  Edge_S5_nonsplit := 38,
  Edge_S4_x_trivial := 39,
  Edge_S4_alone := 40
);
