"""Step 1 of the S17 certificate audit (2026-09-27): E/F/G types, their (sigKey, histogram) buckets,
and the representatives' generators.  Writes types.json (metadata) and types.g (GAP job list).

Why these types: category E is separated only by |Aut| (GAP 4.15.1 AutomorphismGroup may miss
automorphisms, PR #6454), F only by crpfHash (not an isomorphism invariant), G only by
IsomorphismGroups = fail (GAP issue #6537).  A-D rest on order / IdGroup / sigKey / histogram.
"""
import collections, json, random, re
from pathlib import Path

HERE = Path(__file__).resolve().parent
CERT = HERE.parent / "data" / "s17_verification_certificate_v5.g"
CYCLES = HERE.parent / "work" / "s17_subgroups_cycles.g"

types = []
for line in open(CERT):
    if not line.lstrip().startswith("rec("): continue
    m = re.search(r'm:="(\w)"', line).group(1)
    if m not in ("E", "F", "G"): continue
    r = {"t": int(re.search(r"t:=(\d+)", line).group(1)), "i": int(re.search(r"i:=(\d+)", line).group(1)),
         "m": m, "o": int(re.search(r"o:=(\d+)", line).group(1)),
         "sk": re.search(r"sk:=(\[.*?\]\])", line).group(1).replace(" ", ""),
         "h": re.search(r"h:=(\[\[.*?\]\])", line).group(1).replace(" ", "")}
    types.append(r)
buckets = collections.defaultdict(list)
for r in types: buckets[r["sk"] + "|" + r["h"]].append(r["t"])
print(f"{len(types)} E/F/G types in {len(buckets)} (sigKey, histogram) buckets; "
      f"{sum(len(v)*(len(v)-1)//2 for v in buckets.values())} pairs; "
      f"singleton buckets: {sum(1 for v in buckets.values() if len(v) == 1)}")

want = {r["i"] for r in types}
gens, idx, started = {}, 0, False
with open(CYCLES) as f:
    for line in f:
        if not started:
            started = line.strip() == "return ["; continue
        s = line.strip()
        if not s.startswith("["): continue
        idx += 1
        if idx in want: gens[idx] = s.rstrip(",")
assert len(gens) == len(want), (len(gens), len(want))

# Relabelling self-test: the same group conjugated by a random permutation, generators reversed and
# one redundant generator added.  Its fingerprint must equal the original's.
rnd = random.Random(20260927)
selftest = rnd.sample([r["t"] for r in types], 40)
jobs = [{"job": r["t"], "t": r["t"], "i": r["i"], "o": r["o"], "selftest": False} for r in types]
jobs += [{"job": 100000 + t, "t": t, "i": next(r["i"] for r in types if r["t"] == t),
          "o": next(r["o"] for r in types if r["t"] == t), "selftest": True} for t in selftest]
json.dump({"types": types, "buckets": buckets, "selftest": selftest, "jobs": jobs}, open(HERE / "types.json", "w"))
with open(HERE / "types.g", "w", newline="\n") as f:
    f.write("# generated by audit_prepare.py -- representatives of the S17 E/F/G types\nAUDIT_GENS := [];;\n")
    for i in sorted(gens): f.write(f"AUDIT_GENS[{i}] := {gens[i]};;\n")
print(f"{len(jobs)} jobs ({len(selftest)} self-test copies); generators for {len(gens)} representatives written")
