# Triple-Check Dedupe - Worker regular_1
# Auto-generated by prepare_tc_dedupe.py
# Type: regular

SetInfoLevel(InfoWarning, 0);;

# Define S14_TC before loading data
S14_TC := "S14_TC";;

Print("Loading shared library...\n");
Read("/cygdrive/c/Users/jeffr/Downloads/Symmetric Groups/triple_check/dedupe/tc_dedupe_common.g");

Print("Loading group data...\n");
Read("/cygdrive/c/Users/jeffr/Downloads/Symmetric Groups/triple_check/conjugacy_cache/s14_large_invariants_clean.g");
DATA := S14_TC_LARGE;;

Print("Loading bucket assignments...\n");
Read("/cygdrive/c/Users/jeffr/Downloads/Symmetric Groups/triple_check/dedupe/buckets/buckets_regular_1.g");

# Build index lookup for data records
DATA_BY_INDEX := rec();;
for r in DATA do
    DATA_BY_INDEX.(r.index) := r;
od;
Print("Built index lookup for ", Length(DATA), " records\n");

# Initialize checkpoint file
PrintTo("/cygdrive/c/Users/jeffr/Downloads/Symmetric Groups/triple_check/dedupe/checkpoints/checkpoint_regular_1.g",
        "# Worker regular_1 checkpoint file\n",
        "# Started: ", String(Runtime()), "\n\n");

totalReps := [];;
totalGroupsProcessed := 0;;
startTime := Runtime();;

Print("Starting deduplication (regular)...\n");
Print("Processing ", Length(BUCKET_ASSIGNMENTS), " buckets\n\n");

for bucketNum in [1..Length(BUCKET_ASSIGNMENTS)] do
    bucket := BUCKET_ASSIGNMENTS[bucketNum];
    LogProgress(Concatenation("Bucket ", String(bucketNum), "/",
        String(Length(BUCKET_ASSIGNMENTS)), ": ",
        String(Length(bucket.indices)), " groups, key=",
        bucket.key{[1..Minimum(60, Length(bucket.key))]}));

    reps := DeduplicateBucket(bucket.indices, DATA_BY_INDEX);

    totalGroupsProcessed := totalGroupsProcessed + Length(bucket.indices);
    Append(totalReps, reps);

    LogProgress(Concatenation("  Bucket ", String(bucketNum), " complete: ",
        String(Length(bucket.indices)), " -> ", String(Length(reps)), " reps"));
    LogProgress(Concatenation("  Running total: ", String(Length(totalReps)),
        " reps from ", String(bucketNum), " buckets (",
        String(totalGroupsProcessed), " groups processed)"));

    # Checkpoint after each bucket
    AppendTo("/cygdrive/c/Users/jeffr/Downloads/Symmetric Groups/triple_check/dedupe/checkpoints/checkpoint_regular_1.g",
             "# Bucket ", bucketNum, ": ", Length(bucket.indices), " -> ",
             Length(reps), " reps: ", reps, "\n");
od;

# Write final results
elapsed := Runtime() - startTime;;
PrintTo("/cygdrive/c/Users/jeffr/Downloads/Symmetric Groups/triple_check/dedupe/results/result_regular_1.g",
        "# Worker regular_1 results\n",
        "# Completed: ", String(Runtime()), "ms\n",
        "# Elapsed: ", String(elapsed), "ms\n",
        "# Total representatives: ", Length(totalReps), "\n\n",
        "RESULT_REPS_REGULAR_1 := ", totalReps, ";\n");

Print("\n=== COMPLETE === Worker regular_1: ",
      Length(totalReps), " unique representatives from ",
      totalGroupsProcessed, " groups in ",
      Length(BUCKET_ASSIGNMENTS), " buckets (",
      String(Int(elapsed/1000)), "s)\n");
QUIT;
